/*
 * Copyright 2018 Massimo Neri <hello@mneri.me>
 *
 * This file is part of mneri/csv.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package me.mneri.csv.line;

import me.mneri.csv.CsvReader;

import java.io.IOException;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * A CSV line generated by {@link CsvReader}. This class provides getter methods for retrieving column values
 * ({@link RecycledLine#getBoolean}, {@link RecycledLine#getLong}, and so on).
 *
 * @author Massimo Neri &lt;<a href="mailto:hello@mneri.me">hello@mneri.me</a>&gt;
 */
public interface Line {
    /**
     * Return the value of the field at the specified index as {@link BigDecimal}.
     *
     * @param i The index of the field.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    BigDecimal getBigDecimal(int i) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link BigInteger}.
     *
     * @param i The index of the field.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    BigInteger getBigInteger(int i) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link BigInteger} in the radix specified by the second
     * argument.
     *
     * @param i     The index of the field.
     * @param radix The radix to be used.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    BigInteger getBigInteger(int i, int radix) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Boolean}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    boolean getBoolean(int i, boolean def) throws IOException;

    int getCharArray(int i, char[] dest, int start) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Double}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    double getDouble(int i, double def) throws IOException;

    /**
     * Return the number of fields in this line.
     *
     * @return The number of fields.
     */
    int getFieldCount();

    /**
     * Return the value of the field at the specified index as {@link Float}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    float getFloat(int i, float def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Integer}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    int getInteger(int i, int def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Integer} in the radix specified by the second
     * argument. The characters in the string must all be digits of the specified radix, except that the first character
     * may be an ASCII minus sign {@code '-'} an ASCII plus sign {@code '+'}.
     *
     * @param i     The index of the field.
     * @param radix The radix to be used.
     * @param def   The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    int getInteger(int i, int radix, int def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Long}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    long getLong(int i, long def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Long} in the radix specified by the second
     * argument. The characters in the string must all be digits of the specified radix, except that the first character
     * may be an ASCII minus sign {@code '-'} an ASCII plus sign {@code '+'}.
     *
     * @param i     The index of the field.
     * @param radix The radix to be used.
     * @param def   The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    long getLong(int i, int radix, long def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Short}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    short getShort(int i, short def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link Short} in the radix specified by the second
     * argument. The characters in the string must all be digits of the specified radix, except that the first character
     * may be an ASCII minus sign {@code '-'} an ASCII plus sign {@code '+'}.
     *
     * @param i     The index of the field.
     * @param radix The radix to be used.
     * @param def   The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    short getShort(int i, int radix, short def) throws IOException;

    /**
     * Return the value of the field at the specified index as {@link String}.
     *
     * @param i The index of the field.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    String getString(int i) throws IOException;

    /**
     * Return the value of the field at the specified index as an unsigned {@link Integer}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    int getUnsignedInteger(int i, int def) throws IOException;

    /**
     * Return the value of the field at the specified index as an unsigned {@link Long}.
     *
     * @param i   The index of the field.
     * @param def The default value.
     * @return The value of the field.
     * @throws IOException If an I/O error occurs.
     */
    long getUnsignedLong(int i, long def) throws IOException;
}
