/*
 * Copyright 2018 Massimo Neri <hello@mneri.me>
 *
 * This file is part of mneri/csv.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package me.mneri.csv.line;

import me.mneri.csv.reader.CsvReader;

/**
 * A CSV line generated by {@link CsvReader}. This class provides getter methods for retrieving column values
 * ({@link RecycledLine#getBoolean}, {@link RecycledLine#getLong}, and so on).
 * <p>
 * <i>Instances of this class shouldn't be used outside the scope of the method they're provided to because they may be
 * cleaned and reused at any time.</i>
 *
 * @author Massimo Neri &lt;<a href="mailto:hello@mneri.me">hello@mneri.me</a>&gt;
 */
public interface RecycledLine extends Line {
    // This is a marker interface. Its goal is to make it clear to the client that instances of this class shouldn't be
    // returned, stored, or otherwise used outside the scope they're given.
}
